   k_tree.root=Node(17)
    #    k_tree.root.left=Node(5)
    #    k_tree.root.center=Node(6)
    #    k_tree.root.right=Node(10)
    #    k_tree.root.left.left=Node(12)
    #    k_tree.root.left.right=Node(15)
    #    k_tree.root.right.left=Node(30)